# Generated by Django 3.2 on 2023-05-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('email_subject', models.TextField(max_length=1000)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
